# –û–ø–∏—Å–∞–Ω–∏–µ:
# –ó–∞ –æ—Å–Ω–æ–≤—É –±—ã–ª –≤–∑—è—Ç—å –∫–æ–Ω—Ñ–∏–≥ –æ—Ç zxc-rv (https://github.com/zxc-rv/assets/blob/main/config.yaml)
# –í–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –¥–æ—Å—Ç—É–ø–µ–Ω –ø–æ –∞–¥—Ä–µ—Å—É http://192.168.1.1:9090/ui (–≤–º–µ—Å—Ç–æ 192.168.1.1 –º–æ–∂–µ—Ç –±—ã—Ç—å –ª—é–±–æ–π IP, –≥–¥–µ –∑–∞–ø—É—â–µ–Ω –¥–∞–Ω–Ω—ã–π –∫–æ–Ω—Ñ–∏–≥). –ü–æ—Å–ª–µ –¥–æ–±–∞–≤–ª–µ–Ω–∏—è —Å–µ—Ä–≤–µ—Ä–∞ –∏ –∑–∞–ø—É—Å–∫–∞ mihomo –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –∑–∞–π—Ç–∏ –≤ –≤–µ–±-–∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –∏ –≤—ã–±—Ä–∞—Ç—å –Ω—É–∂–Ω–æ–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –¥–ª—è –ø—Ä–æ–∫—Å–∏-–≥—Ä—É–ø–ø
# –ì—Ä—É–ø–ø–∞ "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã" —Å–æ–¥–µ—Ä–∂–∏—Ç —Å–ø–∏—Å–æ–∫ –¥–æ–º–µ–Ω–æ–≤ –±–æ–ª—å—à–∏–Ω—Å—Ç–≤–∞ –∑–∞–±–ª–æ–∫–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö —Ä–µ—Å—É—Ä—Å–æ–≤ (–ë–∞–∑—ã –¥–æ–º–µ–Ω–æ–≤ Zkeen –æ—Ç jameszero)
# My Rules –¥–æ–±–∞–≤–ª–µ–Ω–æ –¥–ª—è –ø—Ä–∏–º–µ—Ä–∞ –¥–æ–±–∞–≤–ª–µ–Ω–∏—è —Å–≤–æ–∏—Ö –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –¥–æ–º–µ–Ω–æ–≤ (–Ω–µ –±–∞–∑) 
# –û—Å—Ç–∞–ª—å–Ω—ã–µ –≥—Ä—É–ø–ø—ã YouTube/Discord –∏ —Ç–¥ –∏–º–µ—é—Ç –ø—Ä–∏–æ—Ä–∏—Ç–µ—Ç –Ω–∞–¥ –≥—Ä—É–ø–ø–æ–π "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã". E—Å–ª–∏ –ø–µ—Ä–µ–æ–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –Ω–µ –Ω—É–∂–Ω–æ, –º–æ–∂–Ω–æ –≤—ã–±—Ä–∞—Ç—å "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã" –≤ –∫–∞—á–µ—Å—Ç–≤–µ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –∏ —É–ø—Ä–∞–≤–ª—è—Ç—å –≤—Å–µ–º–∏ –≥—Ä—É–ø–ø–∞–º–∏ —Ä–∞–∑–æ–º –≤ –≥—Ä—É–ø–ø–µ "–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã"

log-level: silent
allow-lan: true
tproxy-port: 5000
ipv6: false
mode: rule
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile:
  store-selected: true

sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  sniff:
    HTTP:
    TLS:
    QUIC:

proxy-groups:
  - name: –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Reject.png
    include-all: true

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    include-all: true
    proxies:
      - DIRECT
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: Reddit
    type: select
    icon: https://www.redditstatic.com/shreddit/assets/favicon/192x192.png
    include-all: true
    proxies:
      - DIRECT
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/meta.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    include-all: true
    proxies:
      - DIRECT
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    include-all: true
    proxies:
      - DIRECT
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    include-all: true
    proxies:
      - PASS
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    include-all: true
    exclude-filter: üá∑üá∫
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/quic.png
    proxies:
      - REJECT
      - PASS

  - name: PRON
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Pornhub_1.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT
      - REJECT

  - name: My Rules
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cat.png
    include-all: true
    proxies:
      - –ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
      - DIRECT

# –ü—Ä–∏–º–µ—Ä –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è —Å –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ–º –ø–æ–¥–ø–∏—Å–∫–∏ (–£–î–ê–õ–ò–¢–¨, –ï–°–õ–ò –ù–ï –ù–£–ñ–ï–ù!)
proxy-providers:
  proxy-sub:
    type: http
    url: *subscription.link*
    path: ./proxy-providers/proxy-sub.yml
    interval: 3600
    health-check:
      enable: true
      url: http://cp.cloudflare.com/
      interval: 300
      timeout: 2000
      lazy: false
      expected-status: 204
    override:
      udp: true
      tfo: true      

# –ü—Ä–∏–º–µ—Ä vless –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –±–µ–∑ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è –ø–æ–¥–ø–∏—Å–∫–∏ (–£–î–ê–õ–ò–¢–¨, –ï–°–õ–ò –ù–ï –ù–£–ñ–ï–ù!)
proxies:
  - name: vless-reality
    type: vless
    server: *your-server*
    port: 443
    network: tcp
    udp: true
    tls: true
    servername: *your-sni*
    client-fingerprint: chrome
    uuid: *your-uuid*
    flow: xtls-rprx-vision
    reality-opts:
      public-key: *your-pbk*
      short-id: *your-shortid*

rule-providers:
  discord:
    type: inline
    behavior: classical
    format: text
    payload:
      - AND,((DOMAIN-KEYWORD,discord),(NOT,((DOMAIN-SUFFIX,ru))))
      - AND,((IP-CIDR,34.0.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-50100))
      - AND,((IP-CIDR,35.192.0.0/11,no-resolve),(NETWORK,UDP),(DST-PORT,50000-50100))
      - AND,((IP-CIDR,66.22.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-50100))

  cloudflare-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.mrs
    path: ./rule-providers/cloudflare-ips.mrs
    interval: 86400

  telegram-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs
    path: ./rule-providers/telegram-ips.mrs
    interval: 86400

  meta-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/zxc-rv/assets/raw/refs/heads/main/rules/meta-ips.mrs
    path: ./rule-providers/meta-ips.mrs
    interval: 86400

  porn:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-porn.mrs
    path: ./rule-providers/category-porn.mrs
    interval: 86400

  myrules:
    type: inline
    behavior: classical
    format: text
    payload:
      - DOMAIN-SUFFIX,2ip.io

  zkeen_domains_domains:
    type: http
    behavior: classical
    format: text
    url: https://github.com/Anton111111/rule-lists/releases/latest/download/domains.list
    path: ./rule-providers/zkeen_domains_domains.list
    interval: 86400   

  zkeen_domains_other:
    type: http
    behavior: classical
    format: text
    url: https://github.com/Anton111111/rule-lists/releases/latest/download/other.list
    path: ./rule-providers/zkeen_domains_other.list
    interval: 86400

  zkeen_domains_politic:
    type: http
    behavior: classical
    format: text
    url: https://github.com/Anton111111/rule-lists/releases/latest/download/politic.list
    path: ./rule-providers/zkeen_domains_politic.list
    interval: 86400

  zkeen_ip_ru:
    type: http
    behavior: classical
    format: text
    url: https://github.com/Anton111111/rule-lists/releases/latest/download/ru_ips.list
    path: ./rule-providers/zkeen_ip_ru.list
    interval: 86400

rules:
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã # –†–∞–∑–±–ª–æ–∫–∏—Ä–æ–≤–∫–∞ –≤—ã—Å–æ–∫–æ–≥–æ –∫–∞—á–µ—Å—Ç–≤–∞ –Ω–∞ Twitch.tv
  - AND,((NOT,((RULE-SET,zkeen_ip_ru,no-resolve))),(NETWORK,UDP),(DST-PORT,443)),QUIC # –ë–ª–æ–∫–∏—Ä–æ–≤–∫–∞ QUIC –Ω–∞ –í–ù–ï –†–£ (!Zkeen RU IPs)
  - GEOSITE,category-ai-!cn,AI
  - GEOSITE,steam,Steam
  - GEOSITE,spotify,Spotify 
  - GEOSITE,reddit,Reddit
  - OR,((GEOSITE,youtube),(DOMAIN-SUFFIX,googleusercontent.com)),YouTube
  - GEOSITE,twitch,Twitch
  - GEOSITE,twitter,Twitter
  - RULE-SET,discord,Discord
  - OR,((GEOSITE,meta),(RULE-SET,meta-ips,no-resolve)),Meta
  - OR,((GEOSITE,telegram),(RULE-SET,telegram-ips,no-resolve)),Telegram
  - OR,((GEOSITE,cloudflare),(RULE-SET,cloudflare-ips)),Cloudflare
  - RULE-SET,myrules,My Rules
  - RULE-SET,porn,PRON  
  - OR,((RULE-SET,zkeen_domains_domains),(RULE-SET,zkeen_domains_other),(RULE-SET,zkeen_domains_politic)),–ó–∞–±–ª–æ–∫. —Å–µ—Ä–≤–∏—Å—ã
  - MATCH,DIRECT
